os: linux
language: generic
branches:
  only:
    - master

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
           PLAT=manylinux2014_aarch64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/build-wheels.sh
  - ls wheelhouse/

