language: c
services: docker
os: linux

matrix:
  include:
    - os: linux
      arch: arm64
      env:
       - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
       - PLAT=aarch64
    - os: linux
      arch: arm64-graviton2
      env:
       - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
       - PLAT=aarch64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/build-wheels.sh
  - ls wheelhouse/

