language: c
services: docker
os: linux
dist: focal
virt: vm
group: edge

matrix:
  include:
    - os: linux
      arch: amd64
      env:
       - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
       - PLAT=x86_64

    - os: linux
      arch: arm64
      env:
       - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
       - PLAT=aarch64

    - os: linux
      arch: arm64-graviton2
      env:
       - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
       - PLAT=aarch64

install:
  - uname -m
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/build-wheels.sh
  - ls wheelhouse/

