version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - run:
          name: The First step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
