name: Test
on:
  push:
    branches:
       - master

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {name: Linux, python: '3.8', os: ubuntu-latest, tox: py38}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python }}

      - name: Setup up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBUILDWHEEL_BUILD_VERBOSITY: 3
          CIBW_BUILD: "cp37-*"
          CIBW_BEFORE_BUILD: pip install markupsafe==1.1.0 
          CIBW_ARCHS_LINUX: aarch64

      - name: Copy wheel to host
        run: |
          docker image list
          #docker exec -i quay.io/pypa/manylinux2014_aarch64 cp `pip cache list --format=abspath` /root
          docker cp quay.io/pypa/manylinux2014_aarch64:/root/.cache/pip/* .
